# Docker Compose - MCP Server Stack
# Long-running MCP context server with Qdrant dependency
# Services persist across requests (restart: unless-stopped)

networks:
  arbiter-network:
    driver: bridge
    name: arbiter-network

volumes:
  qdrant_storage:
    name: arbiter-qdrant-storage
    driver: local

services:
  # ===========================================================================
  # Qdrant Vector Database
  # ===========================================================================
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: arbiter-qdrant
    restart: unless-stopped  # Persist - no rebuild on requests
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
    networks:
      - arbiter-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ===========================================================================
  # MCP Server - Context API
  # ===========================================================================
  mcp-server:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.mcp-server
      target: production
    container_name: arbiter-mcp-server
    restart: unless-stopped  # Persist - no rebuild on requests
    ports:
      - "3100:3100"  # HTTP API
    environment:
      # Service URLs (Docker networking)
      - QDRANT_URL=http://qdrant:6333
      - AGENT_ORCHESTRATOR_URL=${AGENT_ORCHESTRATOR_URL:-http://agent-orchestrator:3200}

      # MCP Server configuration
      - TRANSPORT=${TRANSPORT:-streamable-http}
      - MCP_HTTP_PORT=${MCP_HTTP_PORT:-3100}

      # Concurrency settings
      - MAX_CONCURRENT_REQUESTS=${MAX_CONCURRENT_REQUESTS:-50}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-30000}

      # Node.js settings
      - NODE_ENV=${NODE_ENV:-production}
      - NODE_OPTIONS=${NODE_OPTIONS:---max-old-space-size=2048}

      # Logging configuration
      - LOG_PREFIX=${LOG_PREFIX:-[ARBITER]}
      - LOG_FORMAT=${LOG_FORMAT:-text}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_USE_COLORS=${LOG_USE_COLORS:-true}
    depends_on:
      qdrant:
        condition: service_started
    networks:
      - arbiter-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
